Repository naveteam/saturn, pull requests merged in 2020-06, with the labels that each got.

#22 [CI]: Alteração no trigger de disparo do GH Action
  .github/workflows/ci.yml
Labels: bug

#21 [Fix] Grid colors
  src/stories/Grid.stories.mdx
Labels: bug, documentation

#19 [Componente] Typography
  src/components/Typography/Caption.jsx
  src/components/Typography/Heading.jsx
  src/components/Typography/Paragraph.jsx
  src/components/Typography/Subtitle.jsx
  src/components/Typography/Typography.jsx
  src/components/Typography/index.js
  src/stories/Typography.stories.mdx
  src/theme/Theme.js
  src/theme/colors.js
  src/theme/fontSizes.js
  src/theme/fontWeights.js
  src/theme/lineHeights.js
Labels: enhancement
